// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: trafic.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusNumber int32 `protobuf:"varint,1,opt,name=BusNumber,proto3" json:"BusNumber,omitempty"`
}

func (x *BusRequest) Reset() {
	*x = BusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trafic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusRequest) ProtoMessage() {}

func (x *BusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trafic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusRequest.ProtoReflect.Descriptor instead.
func (*BusRequest) Descriptor() ([]byte, []int) {
	return file_trafic_proto_rawDescGZIP(), []int{0}
}

func (x *BusRequest) GetBusNumber() int32 {
	if x != nil {
		return x.BusNumber
	}
	return 0
}

type BusScheduleRespons struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusNumber   int32  `protobuf:"varint,1,opt,name=BusNumber,proto3" json:"BusNumber,omitempty"`
	BusSchedule string `protobuf:"bytes,2,opt,name=BusSchedule,proto3" json:"BusSchedule,omitempty"`
}

func (x *BusScheduleRespons) Reset() {
	*x = BusScheduleRespons{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trafic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusScheduleRespons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusScheduleRespons) ProtoMessage() {}

func (x *BusScheduleRespons) ProtoReflect() protoreflect.Message {
	mi := &file_trafic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusScheduleRespons.ProtoReflect.Descriptor instead.
func (*BusScheduleRespons) Descriptor() ([]byte, []int) {
	return file_trafic_proto_rawDescGZIP(), []int{1}
}

func (x *BusScheduleRespons) GetBusNumber() int32 {
	if x != nil {
		return x.BusNumber
	}
	return 0
}

func (x *BusScheduleRespons) GetBusSchedule() string {
	if x != nil {
		return x.BusSchedule
	}
	return ""
}

type TrucLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,1,opt,name=Location,proto3" json:"Location,omitempty"`
}

func (x *TrucLocation) Reset() {
	*x = TrucLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trafic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrucLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrucLocation) ProtoMessage() {}

func (x *TrucLocation) ProtoReflect() protoreflect.Message {
	mi := &file_trafic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrucLocation.ProtoReflect.Descriptor instead.
func (*TrucLocation) Descriptor() ([]byte, []int) {
	return file_trafic_proto_rawDescGZIP(), []int{2}
}

func (x *TrucLocation) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type TraficJamRespons struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsTraficJam bool `protobuf:"varint,1,opt,name=IsTraficJam,proto3" json:"IsTraficJam,omitempty"`
}

func (x *TraficJamRespons) Reset() {
	*x = TraficJamRespons{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trafic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TraficJamRespons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraficJamRespons) ProtoMessage() {}

func (x *TraficJamRespons) ProtoReflect() protoreflect.Message {
	mi := &file_trafic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraficJamRespons.ProtoReflect.Descriptor instead.
func (*TraficJamRespons) Descriptor() ([]byte, []int) {
	return file_trafic_proto_rawDescGZIP(), []int{3}
}

func (x *TraficJamRespons) GetIsTraficJam() bool {
	if x != nil {
		return x.IsTraficJam
	}
	return false
}

var File_trafic_proto protoreflect.FileDescriptor

var file_trafic_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x72, 0x61, 0x66, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x74, 0x72, 0x61, 0x6e, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x2a, 0x0a, 0x0a, 0x42, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x42, 0x75, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x42, 0x75, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x54, 0x0a, 0x12,
	0x42, 0x75, 0x73, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x75, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x42, 0x75, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x20, 0x0a, 0x0b, 0x42, 0x75, 0x73, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x42, 0x75, 0x73, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x22, 0x2a, 0x0a, 0x0c, 0x54, 0x72, 0x75, 0x63, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x34,
	0x0a, 0x10, 0x54, 0x72, 0x61, 0x66, 0x69, 0x63, 0x4a, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x73, 0x54, 0x72, 0x61, 0x66, 0x69, 0x63, 0x4a, 0x61,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x49, 0x73, 0x54, 0x72, 0x61, 0x66, 0x69,
	0x63, 0x4a, 0x61, 0x6d, 0x32, 0x90, 0x02, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x70, 0x6f, 0x72,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42,
	0x75, 0x73, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1c, 0x2e, 0x74, 0x72, 0x61,
	0x6e, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x75, 0x73, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x12, 0x50,
	0x0a, 0x10, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x42, 0x75, 0x73, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x54, 0x72, 0x75, 0x63, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x55, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x72, 0x61, 0x66, 0x69, 0x63,
	0x4a, 0x61, 0x6d, 0x12, 0x1e, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x72, 0x75, 0x63, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x22, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x66, 0x69, 0x63, 0x4a, 0x61, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x42, 0x14, 0x5a, 0x12, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trafic_proto_rawDescOnce sync.Once
	file_trafic_proto_rawDescData = file_trafic_proto_rawDesc
)

func file_trafic_proto_rawDescGZIP() []byte {
	file_trafic_proto_rawDescOnce.Do(func() {
		file_trafic_proto_rawDescData = protoimpl.X.CompressGZIP(file_trafic_proto_rawDescData)
	})
	return file_trafic_proto_rawDescData
}

var file_trafic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_trafic_proto_goTypes = []interface{}{
	(*BusRequest)(nil),         // 0: tranport_service.BusRequest
	(*BusScheduleRespons)(nil), // 1: tranport_service.BusScheduleRespons
	(*TrucLocation)(nil),       // 2: tranport_service.TrucLocation
	(*TraficJamRespons)(nil),   // 3: tranport_service.TraficJamRespons
}
var file_trafic_proto_depIdxs = []int32{
	0, // 0: tranport_service.TranportService.GetBusSchedule:input_type -> tranport_service.BusRequest
	0, // 1: tranport_service.TranportService.TrackBusLocation:input_type -> tranport_service.BusRequest
	2, // 2: tranport_service.TranportService.ReportTraficJam:input_type -> tranport_service.TrucLocation
	1, // 3: tranport_service.TranportService.GetBusSchedule:output_type -> tranport_service.BusScheduleRespons
	2, // 4: tranport_service.TranportService.TrackBusLocation:output_type -> tranport_service.TrucLocation
	3, // 5: tranport_service.TranportService.ReportTraficJam:output_type -> tranport_service.TraficJamRespons
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trafic_proto_init() }
func file_trafic_proto_init() {
	if File_trafic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trafic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trafic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusScheduleRespons); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trafic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrucLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trafic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TraficJamRespons); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trafic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trafic_proto_goTypes,
		DependencyIndexes: file_trafic_proto_depIdxs,
		MessageInfos:      file_trafic_proto_msgTypes,
	}.Build()
	File_trafic_proto = out.File
	file_trafic_proto_rawDesc = nil
	file_trafic_proto_goTypes = nil
	file_trafic_proto_depIdxs = nil
}
